# frozen_string_literal: true

source "https://rubygems.org"

gem "aws-sdk-s3", "~> 1.100"
gem "image_processing", "~> 1.14"
gem "mini_magick", "~> 5.3"
gem "rexml", "~> 3.3"

group :test do
  gem "rspec", "~> 3.13"
end
