# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def address_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def addresses_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_users_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def attendance_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ban_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def cancel_user_registration_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def comment_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def demote_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def destroy_user_session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_event_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_mailing_list_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_poll_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_registration_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def event_attendances_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def event_comments_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def event_polls_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def event_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def events_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def hosted_events_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ical_event_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mailing_list_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mailing_lists_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_event_poll_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_event_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_mailing_list_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_source_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_confirmation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_registration_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def poll_poll_responses_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def poll_response_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def poll_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def promote_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_incinerate_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_reroute_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_sources_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailgun_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_postmark_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_relay_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_sendgrid_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reply_comment_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rsvped_events_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def suspend_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sync_users_mailing_list_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unban_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def undelete_comment_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unsuspend_admin_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_addresses_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_confirmation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_password_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_registration_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_session_url(*args); end
end
