# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedPathHelpersModule`.


module GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def address_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def addresses_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_users_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def attendance_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ban_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def cancel_user_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def comment_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def demote_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def destroy_user_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_event_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_mailing_list_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_poll_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def event_attendances_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def event_comments_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def event_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def event_polls_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def events_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def hosted_events_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ical_event_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mailing_list_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mailing_lists_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_event_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_event_poll_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_mailing_list_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_source_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_confirmation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def poll_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def poll_poll_responses_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def poll_response_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def promote_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_incinerate_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_reroute_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_sources_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailgun_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_health_check_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_postmark_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_relay_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_sendgrid_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reply_comment_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rsvped_events_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def suspend_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def sync_users_mailing_list_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unban_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def undelete_comment_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def unsuspend_admin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_addresses_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_confirmation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_session_path(*args); end
end
