# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 435d2643a0ac40e591e3156a703f597a517004c12d8e901ea26df7e97656b569adc7cfad417782bf948edf5c5939a8c1138372b0b2de826d90e1b0b090e3a84a

test:
  secret_key_base: 006e2c70126cbed446dfee7fc7780a3f491e475ec3a1588a8f03f1705603c15bbed59f2e2b621f6198393e0517905796e0f6eb33835df37d7cff741a052851c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
