local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
test:
  service: Disk
  root: <%= Rails.root.join("storage") %>
amazon:
  service: S3
  region: <%= ENV.fetch("ACTIVE_STORAGE_S3_REGION", "us-east-1") %>
  bucket: <%= ENV["ACTIVE_STORAGE_S3_BUCKET"] %>
  http_open_timeout: 5
  http_read_timeout: 60
