local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
amazon:
  service: S3
  access_key_id: <%= ENV["ACTIVE_STORAGE_AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["ACTIVE_STORAGE_AWS_SECRET_ACCESS_KEY"] %>
  region: "us-east-1"
  bucket: "sjp-partiesforall-files"
